name = "newsworthy-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[d1_databases]]
binding = "DB"
database_name = "newsworthy-db"
database_id = "d92c3799-7ec2-4712-b74d-3054760b2e4f"

[vars]
AGENTBOOK_ADDRESS = "0xd4c3680c8cd5Ef45F5AbA9402e32D0561A1401cc"
FEED_REGISTRY_ADDRESS = "0xb2d538D2BD69a657A5240c446F0565a7F5d52BBF"
NEWS_TOKEN_ADDRESS = "0x2e8B4cB9716db48D5AB98ed111a41daC4AE6f8bF"
NEWS_STAKING_ADDRESS = "0x2d4c0d0a76bA7Ab61b9bed5A6950E216D539CA74"
WORLD_CHAIN_RPC = "https://worldchain-mainnet.g.alchemy.com/v2/tRRCeUyvs7jVWGa5wX85x"
USDC_ADDRESS = "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1"
PAYMENT_RECIPIENT = "0xA145882271662D59362924B3fD2Ed22Df5B9331c"

[ai]
binding = "AI"

# Auto-sync every minute
[triggers]
crons = ["* * * * *"]
